### PR TITLE
Switched to 'gulp-load-plugins'; cleaned up style task

### PR DESCRIPTION
**Pull request by ataylorme**
@jacklenox Really enjoyed your rest API talk at LoopConf.

I've been using gulp for a while and did a bit of cleanup:

* Use [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins)
* Added a `handleErrors` function as a wrapper for `gulp-notify`
* Re-enabled `gulp-autoprefixer` #21 
* Added a `default` task as a wrapper for the existing `watch` task so you can just type `gulp`

I'd be happy to discuss with you in person before the conference is over.

### CODE REVIEW

**Comment by jacklenox** [comment]
@ataylorme Ah, thank you!

The messiness of the gulpfile was one of my hesitations around opening up Picard. These changes are looking great and I'll review them properly asap. As you can probably tell, the file was somewhat cobbled together and I had also been experimenting with Makefiles.

**Comment by ataylorme** [comment]
@jacklenox Cleaned up a little bit more - split gulp tasks out into partial files.

I think a good next step would be integrating [Browsersync](http://www.browsersync.io/docs/gulp/)

**Comment by jacklenox** [comment]
Mmm, I've looked at Browsersync in the past, it looks nice. I'm using the Gulp plugin for [livereload](https://www.npmjs.com/package/gulp-livereload) in a separate Picard-like project.

**Comment by jacklenox** [comment]
So, I've tried building with your modifications and we still have problems with autoprefixer:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Unknown version 6 of ios
```

I'm time-poor right now but I think this is related to the sourcemap, similar to the issues encountered here: https://github.com/sindresorhus/gulp-autoprefixer/issues/20

**Comment by ataylorme** [comment]
> Error: Unknown version 6 of iOS

Looks like the browser prefix parameter. I migrated what was already in use:

*gulp/styles.js, line 10*: ```browsers: [ 'last 3 versions', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4' ]```

Are you open to changing it? Not sure what browser support you are looking to provide.

**Comment by jacklenox** [comment]
No problem changing it. I'm not too fussed about browser support at this stage. We actually have no provision for IE 8 or 9 right now anyway in terms of our routing so there's no need for CSS support there either. I'll be more interested in browser compatibility further down the line.

**Comment by ataylorme** [comment]
@jacklenox I changed it to `[ '> 5%', 'last 2 versions' ]`. Give it a go again.

**Comment by jacklenox** [comment]
All working. I had one remaining issues which was this error appearing when I tried to compile styles:
```
events.js:72 throw er;
// Unhandled 'error' event ^
Error: EMFILE …
```
Apparently this relates to the default OSX limits on how many files can be concurrently opened on OSX. I'm not totally clear why this problem only appeared now, but I followed the fix [here](https://github.com/substack/node-browserify/issues/431) and all seems to be well.

**Pull request merged**
